packaging_format = 2

id = "13ft"
name = "13ft"
description.en = "Bypass paywall by acting as GoogleBot"
description.fr = "Contourner les paywall en vous faisant passer pour GoogleBot"

version = "0.4.1~ynh1"

maintainers = ["Lapineige"]

[upstream]
license = "MIT"
code = "https://github.com/wasi-master/13ft"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/wasi-master/13ft/releases/download/v0.4.1/portable.py"
        sha256 = "2d38da7d3b8a13b7d310f11e93b91d943906f840aa99c565a9a7602b73b3f29f"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "portable.py"
        format = "whatever"
        rename = "portable.py"
        extract = false

        [resources.sources.requirements]
        url = "https://raw.githubusercontent.com/wasi-master/13ft/refs/heads/main/requirements.txt"
        sha256 = "3934941f5ada3b1132dab726e91cf896ba9854b011efa6767bad61ef4717c1d4"
        format = "whatever"
        rename = "requirements.txt"
        extract = false

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
    main.default = 5000

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3-venv, python3-pip"
